#!/usr/bin/zsh

host="host.docker.internal"
port="${DB_PORT:-5432}"
user="${DB_USER:-postgres}"
pass="${DB_PASSWORD:-password}"
version="${PG_VERSION:-12.3}"

if [ -t 1 ]; then
  TTY_OPTS="-it"
else
  TTY_OPTS=""
fi

docker run \
  --rm \
  $TTY_OPTS \
  --mount type=bind,source="$(pwd)",target="$(pwd)" \
  postgres:${version} \
  env PGHOST="${host}" \
  env PGPORT="${port}" \
  env PGUSER="${user}" \
  env PGPASSWORD="${pass}" \
  psql "$@"

